---
name: Test-Database
version: 1.00
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
abstract: Database handles ready for testing
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  DBI: 1
  File::HomeDir: 0.5
  Test::More: 0
  version: 0
provides:
  Test::Database:
    file: lib/Test/Database.pm
    version: 1.00
  Test::Database::Handle:
    file: lib/Test/Database/Handle.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
