name: CI
# See https://perlmaven.com/setup-github-actions for more templates
on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        perl: [ '5.32', '5.36' ]
        exclude:
          - runner: windows-latest
            perl: '5.36'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v3

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}

    - name: Show Perl Version
      run: |
        perl -v

    - name: Install Dist::Zilla
      run: |
        cpanm --notest Dist::Zilla

    - name: Install Modules
      run: |
        dzil authordeps --missing | cpanm --notest
        dzil listdeps --develop --missing | cpanm --notest

    - name: Run tests
      #env:
      #  AUTHOR_TESTING: 1
      #  RELEASE_TESTING: 1
      run: |
        dzil test
